/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IMdiBookOpenVariant: typeof import('~icons/mdi/book-open-variant')['default']
    IMdiBriefcase: typeof import('~icons/mdi/briefcase')['default']
    IMdiFileCode: typeof import('~icons/mdi/file-code')['default']
    IMdiMonitor: typeof import('~icons/mdi/monitor')['default']
    IMdiScriptText: typeof import('~icons/mdi/script-text')['default']
    IMdiShape: typeof import('~icons/mdi/shape')['default']
    IMdiVuejs: typeof import('~icons/mdi/vuejs')['default']
    IMdiXml: typeof import('~icons/mdi/xml')['default']
    SlideContact: typeof import('./src/components/slideTypes/SlideContact.vue')['default']
    SlideContactInfo: typeof import('./src/components/SlideContactInfo.vue')['default']
    SlideContainer: typeof import('./src/components/SlideContainer.vue')['default']
    SlideContainerAbout: typeof import('./src/components/slideContainerTypes/SlideContainerAbout.vue')['default']
    SlideContainerAboutProject: typeof import('./src/components/slideContainerTypes/SlideContainerAboutProject.vue')['default']
    SlideContainerCerts: typeof import('./src/components/slideContainerTypes/SlideContainerCerts.vue')['default']
    SlideContainerHobbies: typeof import('./src/components/slideContainerTypes/SlideContainerHobbies.vue')['default']
    SlideContainerJob: typeof import('./src/components/slideContainerTypes/SlideContainerJob.vue')['default']
    SlideContainerLangs: typeof import('./src/components/slideContainerTypes/SlideContainerLangs.vue')['default']
    SlideContainerPhoto: typeof import('./src/components/slideContainerTypes/SlideContainerPhoto.vue')['default']
    SlideContainerProject: typeof import('./src/components/slideContainerTypes/SlideContainerProject.vue')['default']
    SlideContainerProjectFeature: typeof import('./src/components/slideContainerTypes/SlideContainerProjectFeature.vue')['default']
    SlideContainerProjectSite: typeof import('./src/components/slideContainerTypes/SlideContainerProjectSite.vue')['default']
    SlideContainerSchool: typeof import('./src/components/slideContainerTypes/SlideContainerSchool.vue')['default']
    SlideContainerSection: typeof import('./src/components/SlideContainerSection.vue')['default']
    SlideContainerStack: typeof import('./src/components/slideContainerTypes/SlideContainerStack.vue')['default']
    SlideContainerStackTag: typeof import('./src/components/slideContainerTypes/SlideContainerStackTag.vue')['default']
    SlideContainerTag: typeof import('./src/components/SlideContainerTag.vue')['default']
    SlideEducation: typeof import('./src/components/slideTypes/SlideEducation.vue')['default']
    SlideInfoTab: typeof import('./src/components/SlideInfoTab.vue')['default']
    SlideIntroduction: typeof import('./src/components/slideTypes/SlideIntroduction.vue')['default']
    SlideNavigation: typeof import('./src/components/SlideNavigation.vue')['default']
    SlidePage: typeof import('./src/components/SlidePage.vue')['default']
    SlideProjects: typeof import('./src/components/slideTypes/SlideProjects.vue')['default']
    SlideQuickFact: typeof import('./src/components/SlideQuickFact.vue')['default']
    SlideStack: typeof import('./src/components/slideTypes/SlideStack.vue')['default']
    SlideSummary: typeof import('./src/components/SlideSummary.vue')['default']
    SlideWho: typeof import('./src/components/slideTypes/SlideWho.vue')['default']
    Terminal: typeof import('./src/components/terminalHeroComponents/Terminal.vue')['default']
    Triangle: typeof import('./src/components/3dobjects/Triangle.vue')['default']
  }
}
